spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingService
    username: postgres
    password: Grace@2002
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: bookingService
      port: 27017
      host: localhost
      uri: mongodb://localhost:27017/bookingService
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: c932592c30762c76ea5b
            client-secret: b98c505029fe953010589b5d308a5b4b0ee9ea67
logging:
  level:
    org:
      springframework:
        security: TRACE
